version: 0.0
os: linux

files:
  - source: backend
    destination: /home/admin/workflow-studio-management

hooks:
  ApplicationStop:
    - location: scripts/codedeploy/application_stop.sh
      timeout: 300
  BeforeInstall:
    - location: scripts/codedeploy/before_install.sh
      timeout: 300
  AfterInstall:
    - location: scripts/codedeploy/after_install.sh
      timeout: 300
  ApplicationStart:
    - location: scripts/codedeploy/application_start.sh
      timeout: 300