version: "3.8"

services:
  frontend:
    container_name: angular
    build:
      context: apollo
      dockerfile: Dockerfile
    command: ng serve --host 0.0.0.0
    volumes:
      - ./apollo:/usr/src/app  # for dev
      - .env:/usr/src/app/.env
    restart: unless-stopped
    ports:
      - 4200:4200
    networks:
      - main

  # https://blog.logrocket.com/containerized-development-nestjs-docker/
  backend:
    container_name: nestjs
    build:
      context: backend
      dockerfile: Dockerfile
    command: npm run start:debug
    ports:
      - 3000:3000
      - 9229:9229
    networks:
      - main
    volumes:
      - .env:/usr/src/app/.env
      - ./backend:/usr/src/app
    restart: unless-stopped
    depends_on:
      - database

  # mysql
  database:
    container_name: mysql
    image: mysql:8.4.4
    environment:
      - MYSQL_ROOT_PASSWORD
      - MYSQL_DATABASE
      - MYSQL_USER
      - MYSQL_PASSWORD
    ports:
      - "3306:3306"
    networks:
      - main
    volumes:
      - ./database/data:/var/lib/mysql
    restart: always
  mysql_workbench:
    image: lscr.io/linuxserver/mysql-workbench:latest
    container_name: mysql_workbench
    cap_add:
      - IPC_LOCK
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    # volumes:
    #   - /path/to/config:/config
    ports:
      - 8000:3000
      - 8001:3001
    restart: unless-stopped
    networks:
      - main
networks:
  main:
