on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
env:
  APP_NAME: workflow
  APP_GROUP: on-premise
  REPO: viruskizz/workflow-studio-management
jobs:
  Deploy-Fullstack:
    name: Deploy Angular and NestJS on ${{ inputs.environment }}
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: ap-southeast-1
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      - name: Create Deployment on codedeploy
        run: |
          aws deploy create-deployment \
            --application-name $APP_NAME \
            --deployment-config-name CodeDeployDefault.OneAtATime \
            --deployment-group-name $APP_GROUP \
            --file-exists-behavior OVERWRITE\
            --description "My GitHub deployment demo" \
            --github-location repository=$REPO,commitId=${{ github.sha }}