on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string

jobs:
  lint:
    name: Angular Lint Check
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    defaults:
      run:
        working-directory: ./apollo
    steps:
      - name: Checkout the source code
        uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
          cache-dependency-path: ./apollo/package-lock.json
      - name: Install dependencies
        run: npm ci --legacy-peer-deps
      - name: Run ESLint
        run: npm run lint