name: Main Deployment

on:
  push:
    branches: ["main"]

jobs:
  nest-build:
    name: NestJS Framework Build on Dev
    uses: ./.github/workflows/tpl-nest-build.yml
    with:
      environment: dev
    secrets: inherit
  nest-deploy:
    name: NestJS Framework Deploy on Dev
    needs: ["nest-build"]
    uses: ./.github/workflows/tpl-nest-deploy.yml
    with:
      environment: dev
    secrets: inherit
