name: Main Deployment

on:
  push:
    branches: ["main"]

jobs:
  ng-build:
    name: Angular build on Development
    uses: ./.github/workflows/tpl-angular-build.yml
    with:
      environment: dev
    secrets: inherit
  nest-build:
    name: NestJS Framework Build on Dev
    uses: ./.github/workflows/tpl-nest-build.yml
    with:
      environment: dev
    secrets: inherit
  full-deploy:
    name: Deploy Angular and NestJS
    needs: ["nest-build", "ng-build"]
    uses: ./.github/workflows/tpl-fullstack-deploy.yml
    with:
      environment: dev
    secrets: inherit
