name: Manual Full Deployment
on:
  workflow_dispatch:
    inputs:
      environment:
        type: choice
        options:
        - dev
        - prod
        required: true
        default: dev

jobs:
  ng-build:
    name: Angular build on ${{ inputs.environment }}
    uses: ./.github/workflows/tpl-angular-build.yml
    with:
      environment: ${{ inputs.environment }}
    secrets: inherit
  ng-deploy:
    name: Angular Deploy on ${{ inputs.environment }}
    needs: ["ng-build"]
    uses: ./.github/workflows/tpl-angular-deploy.yml
    with:
      environment: ${{ inputs.environment }}
      refreshCached: true
    secrets: inherit
  nest-build:
    name: NestJS Framework Build on ${{ inputs.environment }}
    uses: ./.github/workflows/tpl-nest-build.yml
    with:
      environment: ${{ inputs.environment }}
    secrets: inherit
  nest-deploy:
    name: NestJS Framework Deploy on ${{ inputs.environment }}
    needs: ["nest-build"]
    uses: ./.github/workflows/tpl-nest-deploy.yml
    with:
      environment: ${{ inputs.environment }}
    secrets: inherit