name: NestJS Framework on PR

on:
  pull_request:
    branches: ["main"]
    paths:
      - backend/**

jobs:
  build:
    name: NestJS Framework Build on Dev
    uses: ./.github/workflows/tpl-nest-build.yml
    with:
      environment: dev
    secrets: inherit
