name: NestJS Framework on PR

on:
  pull_request:
    branches: ["main"]
    paths:
      - backend/**

jobs:
  build:
    name: NestJS Framework Build on Dev
    uses: ./.github/workflows/tpl-nest-build.yml
    with:
      environment: dev
    secrets: inherit
  # deploy:
  #     name: NestJS Framework Deploy on Dev
  #     needs: ["build"]
  #     uses: ./.github/workflows/tpl-nest-deploy.yml
  #     with:
  #       environment: dev
  #     secrets: inherit