name: Angular Build on PR

on:
  pull_request:
    branches: ["main"]
    paths:
      - apollo/**
      - .github/**

jobs:
  lint:
    name: Angular Lint Check on Dev
    uses: ./.github/workflows/tpl-angular-lint.yml
    with:
      environment: dev
    secrets: inherit
  build:
    name: Angular build on Dev
    uses: ./.github/workflows/tpl-angular-build.yml
    with:
      environment: dev
    secrets: inherit
